name: ServerBotForTelegram
description: Plugin that allow connection with Server Bot in Telegram.
main: io.github.robertoccu.serverbotfortelegram.ServerBotForTelegram
version: 1.1.0_log2_1.15.1
api-version: 1.15
author: robertoccu
soft-depend: [Vault]
commands:
    ayuda:
        description: Command to send a help message for server admins.
        aliases: [ayuda]
        usage: /<command> <message>
    priorityTelegram:
        description: Command to send a custom message to priority Telegram chat configured.
        usage: /<command> <message>
    logTelegram:
        description: Command to send a custom message to log Telegram chat configured.
        usage: /<command> <message>
    log2Telegram:
        description: Command to send a custom message to log2 Telegram chat configured.
        usage: /<command> <message>
    publicTelegram:
        description: Command to send a custom message to public Telegram chat configured.
        usage: /<command> <message>
permissions:
    serverBotForTelegram.ayuda:
        description: Allow user to request help.
        default: op
    serverBotForTelegram.sendRawMessages:
        description: Allow user to send custom messages.
        default: op